### ISSUE TITLE
Trying to create document with point.data freezes app

### ISSUE THREAD

**Issue by One2mellow** [beerstorm-net/GeoFlutterFire2#1]
saving only hash or geopoint to firestore works great but when i try to post the object of point.data it freezes my app and doesn't post to firestore

**Comment by zeusbaba** [comment]
thanks for your feedback @One2mellow 

can u plz share code sample on how you are trying to persist `point.data`?   

fyi. i've been using this package since long time, e.g. in [LOC8](https://loc8.app)  
and here is an codesnippet of how i'm persisting into Firestore.
plz let me know if this helps.  

```
CollectionReference collectionReference = FirebaseFirestore.instance.collection("mylocs");

GeoFirePoint geoFirePoint = _geoflutterfire.point(latitude: loc8item.latitude, longitude: loc8item.longitude);

Map<String, dynamic> toSave = Map(); 
toSave['id'] = 'userid';  
// etc etc  
toSave['geofire'] = geoFirePoint.data; // this is to enable geoquerying!!!
await collectionReference.add(toSave);

```

**Comment by zeusbaba** [comment]
I didn't get any feedback from you @One2mellow  , thus I assume that this issue is resolved.  
Feel free to re-open this one or new issues if you need further help.
