### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by lensbreak** [beerstorm-net/GeoFlutterFire2#12]
Hi
 
What exactly is the difference between GeoFlutterFire2 to the other (original) libraries? Like:
https://github.com/DarshanGowda0/GeoFlutterFire
https://github.com/xmany/GeoFlutterFire
https://github.com/mrdishant/flutter_geofire

The readme file is the very same and there are no obvious differences. Why should one prefer your version over another?
 
Second:
Does this package also work for Firebase Realitime Database (I do NOT mean Firestore with realtime capabilities)? If not, which library works for firebase realtime database?
 
Regards

**Comment by zeusbaba** [comment]
see prev issue
https://github.com/beerstorm-net/GeoFlutterFire2/issues/7#issuecomment-1000109807
