### ISSUE TITLE
Query results duplicates after 1250 km 

### ISSUE THREAD

**Issue by enqvida** [beerstorm-net/GeoFlutterFire2#13]
This issue(https://github.com/DarshanGowda0/GeoFlutterFire/issues/57) has been open on Geoflutterfire for almost 2 years. There was even a temporary fix, but it's outdated as well now.

**Comment by FloLecoeuche** [comment]
This is the fix you need ? 
https://github.com/DarshanGowda0/GeoFlutterFire/pull/181

**Comment by enqvida** [comment]
Yeah, that works, and it's our fix actually. I've been waiting on it. Any plans to fix it soon?

**Comment by FloLecoeuche** [comment]
@enqvida please create the PR on this repo so @zeusbaba can review and merge it

**Comment by zeusbaba** [comment]
thnx for your feedback.  
i just included this fix and published [a new version 2.3.14](https://pub.dev/packages/geoflutterfire2)

**Comment by cedvdb** [comment]
@zeusbaba You closed the issue, the PR is not merged.
