### ISSUE TITLE
Compatibility issues with upgraded firebase dependencies

### ISSUE THREAD

**Issue by Chiomsyn** [beerstorm-net/GeoFlutterFire2#17]
This package is not compactible with the upgraded firebase dependencies. 
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3
  firebase_core: ^2.1.1

**Comment by TheFe91** [comment]
There's an open PR on that: #15

**Comment by Chiomsyn** [comment]
ok thanks
