### ISSUE TITLE
Cloud firestore 2.x

### ISSUE THREAD

**Issue by damda58** [beerstorm-net/GeoFlutterFire2#3]
Hello,
Since the update of cloud firestore the format of the documentsnapshot has changed. I can no longer extract my data. could you help me?
Thank you updated

![image](https://user-images.githubusercontent.com/6893451/119658515-8343da80-be2d-11eb-90c1-f65adbef6a79.png)

**Comment by zeusbaba** [comment]
hello @damda58 ,
here is a code snippet you can adapt for your need. let me know if that helps or if you have any further questions.  

```
 // this is the snap data you get from firestore  
...utilisateur...

Map<String, dynamic> snapData = utilisateur.exists ? utilisateur.data() : Map(); 

// now you can read any value from snapData for it is a Map  
// for example   
snapData.containsKey('id') ? snapData['id'] as String : '';  

```

**Comment by damda58** [comment]
Thanks a lot for your help ! it works wonderfully

**Comment by zeusbaba** [comment]
sounds good, you welcome
