### ISSUE TITLE
What's the difference between this package and the original geoflutterfire?

### ISSUE THREAD

**Issue by xmany** [beerstorm-net/GeoFlutterFire2#7]
The document does not say anything about what this package actually does and why should we use this instead of the original one?

Kinda weird

**Comment by ComputelessComputer** [comment]
Same here. I'm curious why this repo was made.

**Comment by zeusbaba** [comment]
this repo was created out of necessity.   
background: I've been using `GeoFlutterFire` package in my apps, and the original repo wasn't updated often enough.  
for some time, I used used my own fork to ensure my apps are stable, thereafter I decided to create a clone and publish it for others might have similar needs as well.   
i'm trying to keep it up2date frequently,
