### ISSUE TITLE
Not compatible with cloud_firestore 3.0.0

### ISSUE THREAD

**Issue by zakblacki** [beerstorm-net/GeoFlutterFire2#8]
Need update

**Comment by CedenoH07** [comment]
Looking for a Update on this one also.

**Comment by Sam-Guru-In-Training** [comment]
Yes, cloud_firestore: ^3.1.4 is needed to work with swanky new flutterfire_ui

**Comment by mitesh77** [comment]
I need as soon as new update in with compatible  => cloud_firestore: ^3.0.0, please do as soon as brother

**Comment by cedvdb** [comment]
Not sure if it works in this case (depends on breaking changes) but you can try:

```yml
dependency_overrides:
  cloud_firestore: ^3.1.5
```

**Comment by HichemFerchi** [comment]
Please and update is required, thank you

**Comment by zeusbaba** [comment]
yesterday, updated dependencies and made a new release `2.3.11`   
please use `geoflutterfire2: ^2.3.11`    
see  https://pub.dev/packages/geoflutterfire2/changelog   

closing this issue, feel free to re-open if you still experience issues
